"""Model layer: attitude representations, inertia, dynamics, and environment.

Every function here is pure. Nothing in this layer reads a file, prints, plots, or
holds mutable state, so each piece can be tested against a closed form result.
"""

from __future__ import annotations

from attitude_control.model.attitude import (
    attitude_error,
    dcm_from_euler321,
    dcm_from_mrp,
    dcm_from_quaternion,
    euler321_from_dcm,
    euler321_from_quaternion,
    is_rotation_matrix,
    mrp_derivative,
    mrp_from_dcm,
    mrp_from_quaternion,
    mrp_shadow,
    mrp_short_rotation,
    principal_angle,
    quaternion_canonical,
    quaternion_conjugate,
    quaternion_derivative,
    quaternion_from_axis_angle,
    quaternion_from_dcm,
    quaternion_from_euler321,
    quaternion_from_mrp,
    quaternion_identity,
    quaternion_multiply,
    quaternion_normalise,
    rotation_vector,
    signed_angle_about,
    skew,
)
from attitude_control.model.dynamics import (
    PlantState,
    body_angular_momentum,
    body_rate_derivative,
    body_torque_from_wheel_torque,
    gyroscopic_torque,
    inertial_angular_momentum,
    rotational_kinetic_energy,
    state_derivative,
)
from attitude_control.model.environment import (
    CircularOrbit,
    ConstantField,
    GravityGradient,
    TiltedDipoleField,
    gravity_gradient_torque,
    magnetic_torque,
)
from attitude_control.model.inertia import (
    Spacecraft,
    WheelArray,
    principal_inertia,
    pyramid_wheel_axes,
    symmetric_inertia,
)

__all__ = [
    "CircularOrbit",
    "ConstantField",
    "GravityGradient",
    "PlantState",
    "Spacecraft",
    "TiltedDipoleField",
    "WheelArray",
    "attitude_error",
    "body_angular_momentum",
    "body_rate_derivative",
    "body_torque_from_wheel_torque",
    "dcm_from_euler321",
    "dcm_from_mrp",
    "dcm_from_quaternion",
    "euler321_from_dcm",
    "euler321_from_quaternion",
    "gravity_gradient_torque",
    "gyroscopic_torque",
    "inertial_angular_momentum",
    "is_rotation_matrix",
    "magnetic_torque",
    "mrp_derivative",
    "mrp_from_dcm",
    "mrp_from_quaternion",
    "mrp_shadow",
    "mrp_short_rotation",
    "principal_angle",
    "principal_inertia",
    "pyramid_wheel_axes",
    "quaternion_canonical",
    "quaternion_conjugate",
    "quaternion_derivative",
    "quaternion_from_axis_angle",
    "quaternion_from_dcm",
    "quaternion_from_euler321",
    "quaternion_from_mrp",
    "quaternion_identity",
    "quaternion_multiply",
    "quaternion_normalise",
    "rotation_vector",
    "rotational_kinetic_energy",
    "signed_angle_about",
    "skew",
    "state_derivative",
    "symmetric_inertia",
]
